#!/bin/bash

# prepares everything for running
echo "Compile CSV -> JS"
cabal install
.cabal-sandbox/bin/timeline data/data.csv > data/entries.js
echo "------"
cat data/entries.js
echo "------"

# webpack
